# Computer Vision

<p>Computer vision is field that deals with how computers can gain high-level understanding from digital images or videos.</p>

## Image

<p>An Image can be represented in the form of pixel matrix</p>
<p>For a black and white image, pixel intensity ranges from 0 to 255</p>
<p> <b>0 - Black </b></p>
<p> <b>255 - white</b> </p>

<p> Color images have 3 channels, <b>Red, Green, Blue</b> </p>

In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
pixel_matrix = np.array([[255,0,255],[0,100,0],[255,0,255]])

In [ ]:
pixel_matrix

In [ ]:
plt.imshow(pixel_matrix,cmap="Greys")

## Image to Matrix

#### Black and White Image
<img src="car_grey.jpg">

In [9]:
car_matrix = plt.imread("car_grey.jpg")

In [10]:
car_matrix.shape

(741, 1200)

In [11]:
print(car_matrix)

[[  5   5   6 ...   4   4   4]
 [  5   6   6 ...   4   4   4]
 [  6   6   6 ...   4   4   4]
 ...
 [169 168 168 ... 157 156 155]
 [176 174 173 ... 156 155 155]
 [175 173 172 ... 156 155 154]]


#### Color Image
<img src="car.jpg">

In [ ]:
car2_matrix = plt.imread("car.jpg")

In [ ]:
car2_matrix.shape

In [ ]:
print(car2_matrix)

## Applications of Computer Vision

### Image Classification

<img src="app4.png" width=700, height=500>

### Object Detection

<img src="app2.png" width=700, height=500>

### Self Driving Cars

<img src="sdc.jpg">

### Face Identification

<img src="app3.jpg">

## OpenCV

<p> OpenCV is an open source library for computer vision and image processing </p>

<p> Initial release - June 2000</p>
<p> Written in C/C++ </p>

### Installation

<p> pip install opencv-contrib-python </p>
<p> conda  install opencv-contrib-python </p>

## Read Image using OpenCV

In [1]:
# import opencv
import cv2

In [ ]:
# read image using imread()
image = cv2.imread("car_grey.jpg")

In [ ]:
# display image with imshow()
cv2.imshow("car",image)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [ ]:
# height and width of image
h,w = image.shape[:2]

In [ ]:
print("height={} , width={}".format(h,w))

## Image Processing

### 1) Resize

In [ ]:
resized = cv2.resize(image,(800,800))

In [ ]:
cv2.imshow("resized",resized)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [ ]:
# Calculating the ratio 

ratio = 800 / w 

# Creating a tuple containing width and height 

dim = (800, int(h * ratio)) 

# Resizing the image 

resize_aspect = cv2.resize(image, dim) 

In [ ]:
cv2.imshow("resized",resize_aspect)
cv2.waitKey(0)
cv2.destroyAllWindows() 

### 2) Rotate

In [ ]:
# Calculating the center of the image 
center = (w // 2, h // 2) 

In [ ]:
# Generating a rotation matrix 
rotation_matrix = cv2.getRotationMatrix2D(center, -45,0.5)

In [ ]:
# Performing the affine transformation 
rotated = cv2.warpAffine(image, rotation_matrix, (w, h)) 

In [ ]:
cv2.imshow("rotated",rotated)
cv2.waitKey(0)
cv2.destroyAllWindows() 

### 3) Color Space

In [2]:
# RGB to GRAY
plane = cv2.imread("plane.bmp")

cv2.imshow("jet",plane)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [ ]:
gray_img = cv2.cvtColor(plane, cv2.COLOR_BGR2GRAY)

In [ ]:
cv2.imshow("gray",gray_img)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [ ]:
# RGB to YUV
#Y is the luminance (brightness) component 
#while U and V are the chrominance (color) components

yuv_img = cv2.cvtColor(plane, cv2.COLOR_BGR2YUV)

cv2.imshow("yuv",yuv_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Split image into RGB
B,G,R = cv2.split(plane)

In [ ]:
cv2.imshow("R",R)
cv2.imshow("G",G)
cv2.imshow("B",B)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Split image into YUV
Y,U,V = cv2.split(yuv_img)
cv2.imshow('Y', Y)
cv2.imshow('U', U)
cv2.imshow('V', V)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# select color space while reading an image
import cv2
plane = cv2.imread("plane.bmp", cv2.IMREAD_GRAYSCALE)

cv2.imshow("jet",plane)
cv2.waitKey(0)
cv2.destroyAllWindows() 

### 4) Flip

In [2]:
# Vertical flip
plane = cv2.imread("plane.bmp")
flipped_vertical = cv2.flip(plane,0)
cv2.imshow('flipped_vertical', flipped_vertical)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Horizontal flip 
flipped_horizontal = cv2.flip(plane,1)
cv2.imshow('flipped_horizontal', flipped_horizontal)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 5) Smoothing and Blur

In [4]:
import numpy as np
plane = cv2.imread('plane.bmp')

In [5]:
kernel_gaussian = np.array([[1,2,1], [2,4,2], [1,2,1]]) / 16.0
kernel_3x3 = np.ones((3,3), np.float32) / 9.0 # Divide by 9 to normalize the kernel
kernel_5x5 = np.ones((5,5), np.float32) / 25.0 # Divide by 25 to normalize the kernel

In [6]:
cv2.imshow('Original', plane)
output = cv2.filter2D(plane, -1, kernel_gaussian)
cv2.imshow('Gaussian filter', output)
output = cv2.filter2D(plane, -1, kernel_3x3)
cv2.imshow('3x3 filter', output)
output = cv2.filter2D(plane, -1, kernel_5x5)
cv2.imshow('5x5 filter', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
output = cv2.blur(plane, (3,3))
cv2.imshow('blur', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 6) Edge Detection

In [21]:
plane = cv2.imread('plane.bmp')

In [22]:
# It is used to indicate depth of cv2.CV_64F.
sobel_horizontal = cv2.Sobel(plane, cv2.CV_64F, 1, 0, ksize=5)
# Kernel size can be: 1,3,5 or 7.
sobel_vertical = cv2.Sobel(plane, cv2.CV_64F, 0, 1, ksize=5)
cv2.imshow('Original', plane)
cv2.imshow('Sobel horizontal', sobel_horizontal)
cv2.imshow('Sobel vertical', sobel_vertical)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
laplacian = cv2.Laplacian(plane, cv2.CV_64F)
cv2.imshow('Original', plane)
cv2.imshow('Laplacian', laplacian)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
canny = cv2.Canny(plane, 50, 240)
cv2.imshow('Canny', canny)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 7) Saving an Image

In [24]:
cv2.imwrite("canny_edge.bmp",canny)

True

### 8) Drawing shapes

In [40]:
plane = cv2.imread('plane.bmp')
cv2.imshow('jet', plane)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
plane_copy = plane.copy()

In [27]:
# Rectangle
top_left_coord = (87,99) #x,y
bottom_right_coord = (164,183) #x,y
color = (255,0,0) #BGR
line_thickness = 2

In [28]:
rectangle = cv2.rectangle(plane_copy,
                          top_left_coord,
                          bottom_right_coord,
                          color,
                          line_thickness)

In [29]:
cv2.imshow("jet",rectangle)
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [35]:
# circle
plane_copy = plane.copy()

In [36]:
center_coord = (120,141) #x,y
radius = 40
color = (255,0,0) #BGR
line_thickness = 2

In [37]:
circle = cv2.circle(plane_copy,
                    center_coord,
                    radius,
                    color,
                    line_thickness)

In [38]:
cv2.imshow("jet",circle)
cv2.waitKey(0)
cv2.destroyAllWindows() 

### 9) Write Text

In [43]:
plane_copy = plane.copy()

In [44]:
text = cv2.putText(plane_copy,               #image 
                   'Fighter Jet',             #text
                   (50,50),                    # coordinates
                   cv2.FONT_HERSHEY_SIMPLEX, # Font 
                   1,                        #Font scale 
                   (0, 255, 0),              # color
                   2)                        # Thickness 

In [45]:
cv2.imshow("jet",text)
cv2.waitKey(0)
cv2.destroyAllWindows() 

## Video

### 1) Access Webcam

In [47]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    cv2.imshow('Input', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

### 2) Read Video File

In [49]:
cap = cv2.VideoCapture("people.mp4")

while True:
    ret, frame = cap.read()
    
    if ret:
        frame = cv2.resize(frame, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA) 
        cv2.imshow('people', frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
    
cap.release()
cv2.destroyAllWindows()

### 3) Face detection Using Haarcascade

In [52]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_alt.xml')
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    face_rects = face_cascade.detectMultiScale(frame, scaleFactor=1.3, minNeighbors=3)
    for (x,y,w,h) in face_rects:
        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0), 3)
    cv2.imshow('Face Detector', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

### 4) Write Video

In [ ]:
cap = cv2.VideoCapture(0)

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')

# file,codec,frames per second,size
output = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while(cap.isOpened()):

    ret, frame = cap.read()
    
    frame = cv2.flip(frame,1)

    # write the flipped frame
    output.write(frame)

    cv2.imshow('frame',frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release everything if job is finished

cap.release()
output.release()
cv2.destroyAllWindows()