In [1]:
import os
#Location of our Train and Test Data For Rock, Paper, Scissor repectively
base_dir = 'RPS'

train_dir = 'RPS/train'
test_dir = 'RPS/test'

train_rock_dir = 'RPS/train/rock'
train_paper_dir = 'RPS/train/paper'
train_scissor_dir = 'RPS/train/scissor'

test_rock_dir = 'RPS/test/rock'
test_paper_dir = 'RPS/test/paper'
test_scissor_dir = 'RPS/test/scissor'

In [2]:
#Importing neccessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D

In [3]:
#MODEL DESIGN
model = Sequential()
#CONVOLUTION LAYER & POOLING LAYER along with RELU Function
model.add(Conv2D(32, (3, 3), activation='relu',input_shape=(150, 150, 3)))
#Convolution helps us identify important deatures in an image. Relu Function makes all negative values zero and 
#gives non linearity
model.add(MaxPooling2D((2, 2)))
#Pooling Downsamples the dimensions of images such that only important features can be focused.
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
#FLATTEN LAYER
# It changes 2d of image into 1d vector for ANN to work on
model.add(Flatten())
#ANN
model.add(Dense(512, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 34, 34, 128)       73856     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 17, 17, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 15, 15, 128)       1

In [4]:
#PREPROCCESSING
#Image data generator expands the dataset to improve performance and to generalize.
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir,target_size=(150, 150),batch_size=32,class_mode='categorical')
test_generator = test_datagen.flow_from_directory(test_dir,target_size=(150, 150),batch_size=32,class_mode='categorical')

Found 1531 images belonging to 3 classes.
Found 657 images belonging to 3 classes.


In [5]:
#Compiling the model to decrease Loss and increase Accuracy over the course of 10 epochs
model.compile(loss='binary_crossentropy',optimizer="adam",metrics=['accuracy'])
mod=model.fit_generator(train_generator,epochs=10)

Epoch 1/10


C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


48/48 [==============================] - 30s 612ms/step - loss: 0.5390 - accuracy: 0.5577
Epoch 2/10
48/48 [==============================] - 29s 609ms/step - loss: 0.1394 - accuracy: 0.9350
Epoch 3/10
48/48 [==============================] - 30s 624ms/step - loss: 0.0678 - accuracy: 0.9665
Epoch 4/10
48/48 [==============================] - 29s 606ms/step - loss: 0.0509 - accuracy: 0.9752
Epoch 5/10
48/48 [==============================] - 29s 599ms/step - loss: 0.0545 - accuracy: 0.9734
Epoch 6/10
48/48 [==============================] - 29s 598ms/step - loss: 0.0146 - accuracy: 0.9940
Epoch 7/10
48/48 [==============================] - 29s 597ms/step - loss: 0.0192 - accuracy: 0.9919
Epoch 8/10
48/48 [==============================] - 29s 603ms/step - loss: 0.0158 - accuracy: 0.9939
Epoch 9/10
48/48 [==============================] - 29s 601ms/step - loss: 0.0170 - accuracy: 0.9880
Epoch 10/10
48/48 [==============================] - 29s 599ms/step - loss: 0.0070 - accuracy: 0.9985


In [6]:
# Evsluating our Test Loss and Accuracy
test_loss, test_accuracy = model.evaluate(test_generator)
print(test_loss)
print(test_accuracy)

21/21 [==============================] - 3s 133ms/step - loss: 0.0332 - accuracy: 0.9848
0.0331830233335495
0.9847792983055115


In [7]:
#Lets provide sample Images to check our models prediction
# Classes are Paper - 0 Rock - 1  Scissor - 2  
# We also change our dimensions to make it simillar to the images during preproccessing
import cv2

In [8]:
img=cv2.imread('Rock.png')
img=cv2.resize(img,(150,150))

In [9]:
#im_array = np.array(img)
#im_array = im_array*(1/225)
#print(im_array)
#img.shape
img = np.array([img]).astype('float64') / 255.0

In [10]:
pre = model.predict(img)
print(pre)

[[1.8914432e-12 1.0000000e+00 5.4057845e-11]]


In [11]:
target_index = np.argmax(pre[0])

In [12]:
prob = np.max(pre[0])

In [13]:
#Class Index
print(target_index)

1


In [14]:
#Class Probability
print(prob)

1.0


In [15]:
img1=cv2.imread('Scissor2.png')
img1=cv2.resize(img1,(150,150))

In [16]:
img1 = np.array([img1]).astype('float64') / 255.0

In [17]:
pre = model.predict(img1)
print(pre)

[[1.575566e-19 9.843154e-25 1.000000e+00]]


In [18]:
target_index = np.argmax(pre[0])

In [19]:
prob = np.max(pre[0])

In [20]:
#Class Index
print(target_index)

2


In [21]:
#Class Probability
print(prob)

1.0


In [22]:
img2=cv2.imread('Paper1.png')
img2=cv2.resize(img2,(150,150))

In [23]:
img2 = np.array([img2]).astype('float64') / 255.0

In [24]:
pre = model.predict(img2)
print(pre)

[[9.9863905e-01 7.9853600e-04 5.6240580e-04]]


In [25]:
target_index = np.argmax(pre[0])

In [26]:
prob = np.max(pre[0])

In [27]:
#Class Index
print(target_index)

0


In [28]:
#Class Probability
print(prob)

0.99863905


In [36]:
#Now lets randomly generate output as per users input move
import random as ran
print('''
Press associated number to the move you want to play
Rock - 1  
Scissor - 2  
Paper - 0
Exit - -1
''')
userin=10
while(True):
    userin = int(input('Enter Your Move:'))
    aiin = ran.randint(0,2)
    if(userin<3 and userin>0):
        if(userin==aiin):
            print('Its a Tie')
            break
        elif(userin==1 and aiin==3):
            print('AI beat you')
            break
        elif(userin==1 and aiin==2):
            print('You beat AI')
            break
        elif(userin==2 and aiin==3):
            print('You beat AI')
            break
        elif(userin==2 and aiin==1):
            print('AI beat you')
            break
        elif(userin==3 and aiin==1):
            print('You beat AI')
            break
        else:
            print('AI beat you')
            break
    else:
        print('Exiting...')
        break

        


Press associated number to the move you want to play
Rock - 1  
Scissor - 2  
Paper - 0
Exit - -1

Enter Your Move:2
Its a Tie
